// This file is generated by RxRequestGenerator script.

import RxSwift
import DataMapper

// Extension for output type SupportedType.
extension RxFetcher {

    public func request(_ endpoint: Endpoint<SupportedType, SupportedType>, input: SupportedType) -> Observable<Response<SupportedType>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request(_ endpoint: Endpoint<Void, SupportedType>) -> Observable<Response<SupportedType>> {
        return observe { self.fetcher.request(endpoint, callback: $0) }
    }

    public func request(_ endpoint: Endpoint<Data, SupportedType>, input: Data) -> Observable<Response<SupportedType>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<IN, SupportedType>, input: IN) -> Observable<Response<SupportedType>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<IN?, SupportedType>, input: IN?) -> Observable<Response<SupportedType>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<[IN], SupportedType>, input: [IN]) -> Observable<Response<SupportedType>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<[IN]?, SupportedType>, input: [IN]?) -> Observable<Response<SupportedType>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<[IN?], SupportedType>, input: [IN?]) -> Observable<Response<SupportedType>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<[IN?]?, SupportedType>, input: [IN?]?) -> Observable<Response<SupportedType>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<[String: IN], SupportedType>, input: [String: IN]) -> Observable<Response<SupportedType>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<[String: IN]?, SupportedType>, input: [String: IN]?) -> Observable<Response<SupportedType>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<[String: IN?], SupportedType>, input: [String: IN?]) -> Observable<Response<SupportedType>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<[String: IN?]?, SupportedType>, input: [String: IN?]?) -> Observable<Response<SupportedType>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }
}

// Extension for output type Void.
extension RxFetcher {

    public func request(_ endpoint: Endpoint<SupportedType, Void>, input: SupportedType) -> Observable<Response<Void>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request(_ endpoint: Endpoint<Void, Void>) -> Observable<Response<Void>> {
        return observe { self.fetcher.request(endpoint, callback: $0) }
    }

    public func request(_ endpoint: Endpoint<Data, Void>, input: Data) -> Observable<Response<Void>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<IN, Void>, input: IN) -> Observable<Response<Void>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<IN?, Void>, input: IN?) -> Observable<Response<Void>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<[IN], Void>, input: [IN]) -> Observable<Response<Void>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<[IN]?, Void>, input: [IN]?) -> Observable<Response<Void>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<[IN?], Void>, input: [IN?]) -> Observable<Response<Void>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<[IN?]?, Void>, input: [IN?]?) -> Observable<Response<Void>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<[String: IN], Void>, input: [String: IN]) -> Observable<Response<Void>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<[String: IN]?, Void>, input: [String: IN]?) -> Observable<Response<Void>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<[String: IN?], Void>, input: [String: IN?]) -> Observable<Response<Void>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<[String: IN?]?, Void>, input: [String: IN?]?) -> Observable<Response<Void>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }
}

// Extension for output type Data.
extension RxFetcher {

    public func request(_ endpoint: Endpoint<SupportedType, Data>, input: SupportedType) -> Observable<Response<Data>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request(_ endpoint: Endpoint<Void, Data>) -> Observable<Response<Data>> {
        return observe { self.fetcher.request(endpoint, callback: $0) }
    }

    public func request(_ endpoint: Endpoint<Data, Data>, input: Data) -> Observable<Response<Data>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<IN, Data>, input: IN) -> Observable<Response<Data>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<IN?, Data>, input: IN?) -> Observable<Response<Data>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<[IN], Data>, input: [IN]) -> Observable<Response<Data>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<[IN]?, Data>, input: [IN]?) -> Observable<Response<Data>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<[IN?], Data>, input: [IN?]) -> Observable<Response<Data>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<[IN?]?, Data>, input: [IN?]?) -> Observable<Response<Data>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<[String: IN], Data>, input: [String: IN]) -> Observable<Response<Data>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<[String: IN]?, Data>, input: [String: IN]?) -> Observable<Response<Data>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<[String: IN?], Data>, input: [String: IN?]) -> Observable<Response<Data>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable>(_ endpoint: Endpoint<[String: IN?]?, Data>, input: [String: IN?]?) -> Observable<Response<Data>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }
}

// Extension for output type OUT.
extension RxFetcher {

    public func request<OUT: Deserializable>(_ endpoint: Endpoint<SupportedType, OUT>, input: SupportedType) -> Observable<Response<OUT>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<OUT: Deserializable>(_ endpoint: Endpoint<Void, OUT>) -> Observable<Response<OUT>> {
        return observe { self.fetcher.request(endpoint, callback: $0) }
    }

    public func request<OUT: Deserializable>(_ endpoint: Endpoint<Data, OUT>, input: Data) -> Observable<Response<OUT>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<IN, OUT>, input: IN) -> Observable<Response<OUT>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<IN?, OUT>, input: IN?) -> Observable<Response<OUT>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[IN], OUT>, input: [IN]) -> Observable<Response<OUT>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[IN]?, OUT>, input: [IN]?) -> Observable<Response<OUT>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[IN?], OUT>, input: [IN?]) -> Observable<Response<OUT>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[IN?]?, OUT>, input: [IN?]?) -> Observable<Response<OUT>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[String: IN], OUT>, input: [String: IN]) -> Observable<Response<OUT>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[String: IN]?, OUT>, input: [String: IN]?) -> Observable<Response<OUT>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[String: IN?], OUT>, input: [String: IN?]) -> Observable<Response<OUT>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[String: IN?]?, OUT>, input: [String: IN?]?) -> Observable<Response<OUT>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }
}

// Extension for output type [OUT].
extension RxFetcher {

    public func request<OUT: Deserializable>(_ endpoint: Endpoint<SupportedType, [OUT]>, input: SupportedType) -> Observable<Response<[OUT]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<OUT: Deserializable>(_ endpoint: Endpoint<Void, [OUT]>) -> Observable<Response<[OUT]>> {
        return observe { self.fetcher.request(endpoint, callback: $0) }
    }

    public func request<OUT: Deserializable>(_ endpoint: Endpoint<Data, [OUT]>, input: Data) -> Observable<Response<[OUT]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<IN, [OUT]>, input: IN) -> Observable<Response<[OUT]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<IN?, [OUT]>, input: IN?) -> Observable<Response<[OUT]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[IN], [OUT]>, input: [IN]) -> Observable<Response<[OUT]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[IN]?, [OUT]>, input: [IN]?) -> Observable<Response<[OUT]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[IN?], [OUT]>, input: [IN?]) -> Observable<Response<[OUT]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[IN?]?, [OUT]>, input: [IN?]?) -> Observable<Response<[OUT]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[String: IN], [OUT]>, input: [String: IN]) -> Observable<Response<[OUT]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[String: IN]?, [OUT]>, input: [String: IN]?) -> Observable<Response<[OUT]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[String: IN?], [OUT]>, input: [String: IN?]) -> Observable<Response<[OUT]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[String: IN?]?, [OUT]>, input: [String: IN?]?) -> Observable<Response<[OUT]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }
}

// Extension for output type [OUT?].
extension RxFetcher {

    public func request<OUT: Deserializable>(_ endpoint: Endpoint<SupportedType, [OUT?]>, input: SupportedType) -> Observable<Response<[OUT?]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<OUT: Deserializable>(_ endpoint: Endpoint<Void, [OUT?]>) -> Observable<Response<[OUT?]>> {
        return observe { self.fetcher.request(endpoint, callback: $0) }
    }

    public func request<OUT: Deserializable>(_ endpoint: Endpoint<Data, [OUT?]>, input: Data) -> Observable<Response<[OUT?]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<IN, [OUT?]>, input: IN) -> Observable<Response<[OUT?]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<IN?, [OUT?]>, input: IN?) -> Observable<Response<[OUT?]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[IN], [OUT?]>, input: [IN]) -> Observable<Response<[OUT?]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[IN]?, [OUT?]>, input: [IN]?) -> Observable<Response<[OUT?]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[IN?], [OUT?]>, input: [IN?]) -> Observable<Response<[OUT?]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[IN?]?, [OUT?]>, input: [IN?]?) -> Observable<Response<[OUT?]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[String: IN], [OUT?]>, input: [String: IN]) -> Observable<Response<[OUT?]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[String: IN]?, [OUT?]>, input: [String: IN]?) -> Observable<Response<[OUT?]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[String: IN?], [OUT?]>, input: [String: IN?]) -> Observable<Response<[OUT?]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[String: IN?]?, [OUT?]>, input: [String: IN?]?) -> Observable<Response<[OUT?]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }
}

// Extension for output type [String: OUT].
extension RxFetcher {

    public func request<OUT: Deserializable>(_ endpoint: Endpoint<SupportedType, [String: OUT]>, input: SupportedType) -> Observable<Response<[String: OUT]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<OUT: Deserializable>(_ endpoint: Endpoint<Void, [String: OUT]>) -> Observable<Response<[String: OUT]>> {
        return observe { self.fetcher.request(endpoint, callback: $0) }
    }

    public func request<OUT: Deserializable>(_ endpoint: Endpoint<Data, [String: OUT]>, input: Data) -> Observable<Response<[String: OUT]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<IN, [String: OUT]>, input: IN) -> Observable<Response<[String: OUT]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<IN?, [String: OUT]>, input: IN?) -> Observable<Response<[String: OUT]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[IN], [String: OUT]>, input: [IN]) -> Observable<Response<[String: OUT]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[IN]?, [String: OUT]>, input: [IN]?) -> Observable<Response<[String: OUT]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[IN?], [String: OUT]>, input: [IN?]) -> Observable<Response<[String: OUT]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[IN?]?, [String: OUT]>, input: [IN?]?) -> Observable<Response<[String: OUT]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[String: IN], [String: OUT]>, input: [String: IN]) -> Observable<Response<[String: OUT]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[String: IN]?, [String: OUT]>, input: [String: IN]?) -> Observable<Response<[String: OUT]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[String: IN?], [String: OUT]>, input: [String: IN?]) -> Observable<Response<[String: OUT]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[String: IN?]?, [String: OUT]>, input: [String: IN?]?) -> Observable<Response<[String: OUT]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }
}

// Extension for output type [String: OUT?].
extension RxFetcher {

    public func request<OUT: Deserializable>(_ endpoint: Endpoint<SupportedType, [String: OUT?]>, input: SupportedType) -> Observable<Response<[String: OUT?]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<OUT: Deserializable>(_ endpoint: Endpoint<Void, [String: OUT?]>) -> Observable<Response<[String: OUT?]>> {
        return observe { self.fetcher.request(endpoint, callback: $0) }
    }

    public func request<OUT: Deserializable>(_ endpoint: Endpoint<Data, [String: OUT?]>, input: Data) -> Observable<Response<[String: OUT?]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<IN, [String: OUT?]>, input: IN) -> Observable<Response<[String: OUT?]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<IN?, [String: OUT?]>, input: IN?) -> Observable<Response<[String: OUT?]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[IN], [String: OUT?]>, input: [IN]) -> Observable<Response<[String: OUT?]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[IN]?, [String: OUT?]>, input: [IN]?) -> Observable<Response<[String: OUT?]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[IN?], [String: OUT?]>, input: [IN?]) -> Observable<Response<[String: OUT?]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[IN?]?, [String: OUT?]>, input: [IN?]?) -> Observable<Response<[String: OUT?]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[String: IN], [String: OUT?]>, input: [String: IN]) -> Observable<Response<[String: OUT?]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[String: IN]?, [String: OUT?]>, input: [String: IN]?) -> Observable<Response<[String: OUT?]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[String: IN?], [String: OUT?]>, input: [String: IN?]) -> Observable<Response<[String: OUT?]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }

    public func request<IN: Serializable, OUT: Deserializable>(_ endpoint: Endpoint<[String: IN?]?, [String: OUT?]>, input: [String: IN?]?) -> Observable<Response<[String: OUT?]>> {
        return observe { self.fetcher.request(endpoint, input: input, callback: $0) }
    }
}
