language: objective-c
osx_image: xcode10.2

before_install:
    - pod repo update --silent

script:
    - (xcodebuild -workspace Fetcher.xcworkspace -scheme Fetcher -sdk iphonesimulator build-for-testing | egrep -A 3 "(error|warning|note):\ "; exit ${PIPESTATUS[0]})
    - xctool -workspace Fetcher.xcworkspace -scheme Fetcher -sdk iphonesimulator run-tests
    - pod lib lint --no-clean

notifications:
    slack: brightify:00rIGJIfWqG5RyWCVoRNEgxt
